# Generated by Django 4.2.25 on 2025-10-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_contrato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('documento', models.FileField(blank=True, null=True, upload_to='sueldos_documentos/')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sueldos', to='sueldos.trabajador')),
            ],
        ),
    ]
