# Generated by Django 4.2.25 on 2025-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0002_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_costo_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
