# Generated by Django 4.2.25 on 2025-10-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0002_alter_cliente_correo_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
