# Generated by Django 4.2.25 on 2025-10-14 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_rental', '0005_productocompra_compraproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompraProducto',
            new_name='Compra2',
        ),
    ]
