# Generated by Django 4.2.25 on 2025-10-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0006_rename_compraproducto_compra2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_rental.compra2'),
        ),
    ]
