# Generated by Django 4.2.25 on 2025-10-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0008_compracamiones_pagocamiones_ventacamiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compracamiones',
            name='pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
