# Generated by Django 4.2.25 on 2025-10-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0009_alter_compracamiones_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compracamiones',
            name='pagado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
