# Generated by Django 4.2.25 on 2025-10-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0011_ordencompra_detalleorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
