# Generated by Django 4.2.25 on 2025-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0012_alter_producto_fecha_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroOrdenDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
