# Generated by Django 4.2.25 on 2025-10-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0013_numeroordendisponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocompra',
            name='codigo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
