# Generated by Django 4.2.25 on 2025-10-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0014_productocompra_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateField()),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(max_length=255)),
            ],
        ),
    ]
