# Generated by Django 4.2.25 on 2025-10-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0015_productonuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='producto_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_rental.productonuevo'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_rental.producto'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
