# Generated by Django 4.2.25 on 2025-11-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0016_detalleorden_producto_nuevo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productonuevo',
            name='precio_unitario',
        ),
    ]
