# Generated by Django 4.2.25 on 2025-11-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0017_remove_productonuevo_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema_rental.cliente'),
            preserve_default=False,
        ),
    ]
