# Generated by Django 4.2.25 on 2025-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0020_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
