# Generated by Django 4.2.25 on 2025-11-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0022_producto_impuesto_producto_neto_producto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
