# Generated by Django 4.2.25 on 2025-11-10 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_rental', '0023_producto_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocompra',
            name='fecha_compra',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
