# Generated by Django 4.2.25 on 2025-11-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPagoCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('disponibilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arriendo', models.PositiveIntegerField()),
                ('seca', models.PositiveIntegerField()),
                ('horas_adicionales', models.PositiveIntegerField()),
                ('valor_neto', models.PositiveIntegerField()),
                ('iva', models.PositiveIntegerField()),
                ('valor_total', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_pago', to='camiones.camion')),
            ],
        ),
    ]
