# Generated by Django 4.2.25 on 2025-11-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0002_estadopagocamion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArriendoCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor_por_dia', models.PositiveIntegerField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriendos', to='camiones.camion')),
            ],
        ),
    ]
