# Generated by Django 4.2.25 on 2025-11-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0003_arriendocamion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadopagocamion',
            name='arriendo',
        ),
        migrations.RemoveField(
            model_name='estadopagocamion',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='estadopagocamion',
            name='horas_adicionales',
        ),
        migrations.RemoveField(
            model_name='estadopagocamion',
            name='seca',
        ),
        migrations.RemoveField(
            model_name='estadopagocamion',
            name='valor_neto',
        ),
        migrations.RemoveField(
            model_name='estadopagocamion',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='anticipo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='avance_a_la_fecha',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='descuento_especial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='descuentos_multas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='devolucion_anticipo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='devolucion_seguro',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='estado_pago_anterior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='presente_estado_pago',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='retencion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='total_a_pagar',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='total_estado_pago',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadopagocamion',
            name='iva',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
