# Generated by Django 4.2.25 on 2025-11-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0004_remove_estadopagocamion_arriendo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadopagocamion',
            old_name='subtotal',
            new_name='arriendo',
        ),
        migrations.RenameField(
            model_name='estadopagocamion',
            old_name='total_estado_pago',
            new_name='horas_adicionales',
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='disponibilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='seca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='valor_neto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='valor_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadopagocamion',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
    ]
