# Generated by Django 4.2.25 on 2025-11-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0005_rename_subtotal_estadopagocamion_arriendo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadopagocamion',
            old_name='arriendo',
            new_name='devolucion_retenciones',
        ),
        migrations.RenameField(
            model_name='estadopagocamion',
            old_name='horas_adicionales',
            new_name='nuevo_saldo_anticipo',
        ),
        migrations.RenameField(
            model_name='estadopagocamion',
            old_name='seca',
            new_name='nuevo_saldo_retenciones',
        ),
        migrations.RenameField(
            model_name='estadopagocamion',
            old_name='valor_neto',
            new_name='saldo_anterior_anticipo',
        ),
        migrations.RenameField(
            model_name='estadopagocamion',
            old_name='valor_total',
            new_name='saldo_anterior_retenciones',
        ),
        migrations.RemoveField(
            model_name='estadopagocamion',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='subtotal_con_descuento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadopagocamion',
            name='total_estado_pago',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadopagocamion',
            name='descuento_especial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
