# Generated by Django 4.2.25 on 2025-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0007_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='numero_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
