# Generated by Django 4.2.25 on 2025-11-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcontrato', models.CharField(help_text='Nombre del camión o subcontrato', max_length=100)),
                ('obra', models.CharField(help_text='Nombre de la obra (ingresado manualmente)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o referencia del contrato', max_length=100)),
                ('periodo', models.CharField(help_text='Ej: 01-11-2025 al 30-11-2025', max_length=50)),
                ('uf_pactada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uf_del_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_compra', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='camion.camion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('avance_a_la_fecha', models.PositiveIntegerField()),
                ('estado_pago_anterior', models.PositiveIntegerField()),
                ('devolucion_seguro', models.PositiveIntegerField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_pago', to='camion.contrato')),
            ],
        ),
    ]
