# Generated by Django 4.2.25 on 2025-11-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='obra',
        ),
        migrations.AddField(
            model_name='camion',
            name='obras',
            field=models.TextField(default='Sin obra asignada'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='subcontrato',
            field=models.CharField(max_length=100),
        ),
    ]
