# Generated by Django 4.2.25 on 2025-11-13 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camion', '0002_remove_camion_obra_camion_obras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadopago',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='estadopago',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='estadopago',
            name='numero',
        ),
        migrations.AddField(
            model_name='estadopago',
            name='camion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estados_pago', to='camion.camion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadopago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadopago',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='fecha_termino',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='obra',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadopago',
            name='uf_del_dia',
            field=models.DecimalField(decimal_places=2, default=39500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadopago',
            name='uf_pactada',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10),
            preserve_default=False,
        ),
    ]
