# Generated by Django 4.2.25 on 2025-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_ventas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
