# Generated by Django 4.2.25 on 2025-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_facturaventa_libroventa_delete_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_ventas/'),
        ),
    ]
