# Generated by Django 4.2.25 on 2025-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_facturaventa_boucher_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='monto_exento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='monto_iva',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='monto_neto',
            field=models.FloatField(default=0),
        ),
    ]
