# Generated by Django 4.2.25 on 2025-11-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_facturaventa_monto_exento_facturaventa_monto_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='origen_libro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
