# Generated by Django 4.2.25 on 2025-10-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagoF29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_f29/')),
            ],
        ),
        migrations.CreateModel(
            name='PagoPreviRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_previred/')),
            ],
        ),
    ]
