# Generated by Django 4.2.25 on 2025-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroOtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cotizacion', 'Cotización'), ('ajuste', 'Ajuste'), ('nota', 'Nota interna'), ('gasto', 'Gasto menor'), ('otro', 'Otro'), ('patente', 'Patente'), ('licencia', 'Licencia'), ('mantenimiento', 'Mantenimiento'), ('servicio', 'Servicio'), ('suscripcion', 'Suscripción'), ('impuesto', 'Impuesto'), ('multas', 'Multas'), ('seguros', 'Seguros'), ('honorarios', 'Honorarios'), ('comisiones', 'Comisiones'), ('publicidad', 'Publicidad'), ('viajes', 'Viajes'), ('capacitación', 'Capacitación'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_otros/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
