# Generated by Django 4.2.25 on 2025-10-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrootro',
            name='tipo',
            field=models.CharField(choices=[('partes', 'Partes'), ('boletas', 'Boletas'), ('patentes', 'Patentes'), ('otros', 'Otros')], max_length=20),
        ),
    ]
