# Generated by Django 4.2.25 on 2025-10-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoInicialMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'unique_together': {('año', 'mes')},
            },
        ),
    ]
