# Generated by Django 4.2.25 on 2025-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoinicialmensual',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
