# Generated by Django 4.2.25 on 2025-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('archivo', models.FileField(upload_to='libros_compras/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
