# Generated by Django 4.2.25 on 2025-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librocompra',
            name='estado',
            field=models.CharField(choices=[('procesando', 'Procesando'), ('correcto', 'Correctamente procesado'), ('error', 'Error al procesar')], default='procesando', max_length=20),
        ),
    ]
