# Generated by Django 4.2.25 on 2025-10-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_librocompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField()),
                ('proveedor', models.CharField(max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('origen_libro', models.DateField()),
            ],
        ),
    ]
