# Generated by Django 4.2.25 on 2025-10-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_facturacompra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibroCompra',
        ),
    ]
