# Generated by Django 4.2.25 on 2025-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_delete_librocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='rut_proveedor',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
