# Generated by Django 4.2.25 on 2025-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_facturacompra_rut_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del libro subido')),
                ('archivo', models.FileField(help_text='Archivo original del libro CSV', upload_to='libros/')),
            ],
        ),
    ]
