# Generated by Django 4.2.25 on 2025-10-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_librocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_compras/'),
        ),
    ]
