# Generated by Django 4.2.25 on 2025-10-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_facturacompra_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='boucher_pago',
            field=models.FileField(blank=True, null=True, upload_to='bouchers_pagos_compras/'),
        ),
    ]
