# Generated by Django 4.2.25 on 2025-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_facturacompra_boucher_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='monto_excento',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='monto_neto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
