# Generated by Django 4.2.25 on 2025-11-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_facturacompra_monto_excento_facturacompra_monto_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacompra',
            name='monto_excento',
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='monto_exento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='monto_iva',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='monto_neto',
            field=models.FloatField(default=0),
        ),
    ]
